version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://moscrm:${MONGO_PASSWORD}@mongo:27017/clinicdb?authSource=admin
      NODE_ENV: production
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: moscrm
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    command: [--auth]
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network: