services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://admin:admin123@81.196.46.41:27017/clinicdb?authSource=admin
