name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no user@your_vps_ip << 'EOF'
          cd /home/user/app
          git pull origin main
          docker-compose down
          docker-compose up -d --build
          EOF